services:
  auth:
    build:
      dockerfile: ./Dockerfile
      context: ./auth_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_DB=${DATABASE_DB}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=db
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SES_FROM_EMAIL=${SES_FROM_EMAIL}
      - VERIFY_KEY=${VERIFY_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped

  core:
    build:
      dockerfile: ./Dockerfile
      context: ./core_service
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_started
    environment:
      - DATABASE_DB=${DATABASE_DB}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=db
      - YANDEX_FOLDER_ID=${YANDEX_FOLDER_ID}
      - YANDEX_API_KEY=${YANDEX_API_KEY}
    ports:
      - "8001:8001"
    restart: unless-stopped

  db:
    image: postgres:16.4
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_CORE_API_URL=http://localhost:8001
    depends_on:
      - auth
      - core
    restart: unless-stopped

volumes:
  postgres_data:
